- name: Installing stow brew
  homebrew:
    name: stow
  tags:
    - install
    - dotfiles
    - stow
  when: ansible_distribution == 'MacOSX'
- name: Installing stow apt
  become: true
  apt:
    name: ["stow"]
  tags:
    - install
    - dotfiles
    - stow
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:jrgirvan/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow

