- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: download neovim nightly deb
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb"
    dest: /tmp/nvim-linux64.deb
    mode: 0440
  tags:
    - install
    - neovim

- name: install neovim deb
  apt: deb="/tmp/nvim-linux64.deb"
  become: true
  tags:
    - install
    - neovim
