- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "darktable", "direnv" ]
  tags:
    - install
    - productivity

